version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install --silent --no-progress -g serverless

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - echo starting severless deployment...
      - serverless deploy --stage $env  --region $region --conceal --verbose
      - echo Finished deployment

  post_build:
    commands:
      - echo Build completed successfully!

